/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockTickerRouteImport } from './routes/stock/$ticker'
import { Route as InvestorIdRouteImport } from './routes/investor/$id'

const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTickerRoute = StockTickerRouteImport.update({
  id: '/stock/$ticker',
  path: '/stock/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorIdRoute = InvestorIdRouteImport.update({
  id: '/investor/$id',
  path: '/investor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/investors': typeof InvestorsRoute
  '/investor/$id': typeof InvestorIdRoute
  '/stock/$ticker': typeof StockTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/investors': typeof InvestorsRoute
  '/investor/$id': typeof InvestorIdRoute
  '/stock/$ticker': typeof StockTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/investors': typeof InvestorsRoute
  '/investor/$id': typeof InvestorIdRoute
  '/stock/$ticker': typeof StockTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/investors'
    | '/investor/$id'
    | '/stock/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analysis' | '/investors' | '/investor/$id' | '/stock/$ticker'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/investors'
    | '/investor/$id'
    | '/stock/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  InvestorsRoute: typeof InvestorsRoute
  InvestorIdRoute: typeof InvestorIdRoute
  StockTickerRoute: typeof StockTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$ticker': {
      id: '/stock/$ticker'
      path: '/stock/$ticker'
      fullPath: '/stock/$ticker'
      preLoaderRoute: typeof StockTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/$id': {
      id: '/investor/$id'
      path: '/investor/$id'
      fullPath: '/investor/$id'
      preLoaderRoute: typeof InvestorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  InvestorsRoute: InvestorsRoute,
  InvestorIdRoute: InvestorIdRoute,
  StockTickerRoute: StockTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
